// <auto-generated />
using BooksMVC.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksMVC.Migrations
{
    [DbContext(typeof(BooksDataContext))]
    partial class BooksDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BooksMVC.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InInventory")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Thoreau",
                            InInventory = true,
                            NumberOfPages = 212,
                            Title = "Walden"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Emerson",
                            InInventory = true,
                            NumberOfPages = 253,
                            Title = "Nature"
                        },
                        new
                        {
                            Id = 3,
                            Author = "C.G. Jung",
                            InInventory = false,
                            NumberOfPages = 332,
                            Title = "Memories, Dreams, Reflections"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
